version: '3.7'

services:
  redis:
    image: redis:alpine

  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    env_file:
      - pg.env
    volumes:
      - pg-data:/var/lib/postgresql/data/

volumes:
  pg-data:
